### ISSUE TITLE
[Templating] provide default templates if none is found for a given action.

### ISSUE THREAD

**Issue by docteurklein** [KnpLabs/geekweek12#13]
We could have default templates for edit, new, show, list.

For example, if `src/App/Resources/views/<controller>/new.html.twig` is not found, 
fallback to `src/Knp/RadBundle//Resources/views/Default/new.html.twig`.

**Comment by docteurklein** [comment]
Could be doable in the ViewListener.

**Comment by gquemener** [comment]
absolutly! :+1:
