### ISSUE TITLE
[templating] auto create a default title from routing info.

### ISSUE THREAD

**Issue by docteurklein** [KnpLabs/geekweek12#17]
This way, we could have kindof a breadcrumb in browser toolbar.

Example: When I am in CheesesController::editAction:

result would be :

``` html
<head>
     <title>Edit Cheese ::Cheeses</title>
</head>

```

**Comment by everzet** [comment]
I though about putting route info into `defaults` in routing loader for that.

**Comment by docteurklein** [comment]
Yes. something like that, and then use `app.request.attributes` in the base layout to display them in the title block.

At least more useful than the sooo usual "Welcome!" on all the website.
