### ISSUE TITLE
Magical action rendering doesn't work with twig render block

### ISSUE THREAD

**Issue by gquemener** [KnpLabs/geekweek12#2]
The current behavior which consist in returning an array in an action and create a corresponding template doesn't work when using the twig render block.

Here's an example:

``` html
src/App/Resources/views/base.html.twig
        <div class="container">
            <div class="row">
                <div class="span4">
                    {% render 'App:Cheese:listRegion' %}
                </div>
            </div>
        </div>
```

``` php
src/App/Controller/CheeseController.php
    public function listRegionAction()
    {
        return array('regions' => $this->getRepository()->findRegions());
    }
```

will give the following exception:
`An exception has been thrown during the rendering of a template ("The controller must return a response (Array(regions => Array()) given).") in "App:Cheese:index.html.twig".`

**Comment by docteurklein** [comment]
seems related to #4 .  Both are about sub requests handled by the http kernel. From what i see, the `kernel.view` listeners should be called whatever the request type is.

**Comment by everzet** [comment]
It's been fixed on thursday.
