### ISSUE TITLE
French range of mountains Accent

### ISSUE THREAD

**Issue by pborreli** [KnpLabs/geekweek12#6]
Pyrenées  => Pyrénées

**Comment by cordoval** [comment]
oh boy, but rightly said

**Comment by PedroTroller** [comment]
Fixed https://github.com/KnpLabs/geekweek12/commit/c0ca8caec3d7e0f899fb7f2ba55265c57285dd77

**Comment by pborreli** [comment]
you forgot features/browse_categories.feature

**Comment by PedroTroller** [comment]
Done again https://github.com/KnpLabs/geekweek12/commit/e052d6fd9d372fd8ab02d4120a5b5ca98a02b45f

**Comment by pborreli** [comment]
thanks
